name: panhandler
label: Panhandler

repositories:
  - name: Iron-Skillet-v81
    url: https://github.com/PaloAltoNetworks/iron-skillet.git
    branch: panos_v8.1
    destination_directory: Iron-Skillet v81
  - name: Iron-Skillet-v80
    url: https://github.com/PaloAltoNetworks/iron-skillet.git
    branch: panos_v8.0
    destination_directory: Iron-Skillet v80
  - name: Mobile Skillets
    url: https://github.com/PaloAltoNetworks/MobileSkillet.git
    branch: panos_v8.1
    destination_directory: Mobile Skillet v81
  - name: MSSP Templates v8.1
    url:  https://github.com/scotchoaf/mssp-templates.git
    branch: panos_v8.1
    destination_directory: MSSP Skillets v81
  - name: Default Skillets
    url: https://github.com/PaloAltoNetworks/Skillets.git
    branch: master
    destination_directory: Default Skillets

views:
  - name: ''
    class: CNCView
    menu: Panhandler
    menu_option: Welcome
    attributes:
      template_name: panhandler/welcome.html
    context:
      title: Panhandler
      description: description is inline
      documentation_link: https://panhandler.readthedocs.io/en/latest/
      next: repos

  - name: import
    class: ImportRepoView
    menu: Panhandler
    menu_option: Import Templates
    attributes:
      snippet: import_repo
      header: Import Repository
      title: Enter a valid git url and desired branch below
      next_url: view_snippets
      help_text: >
        This view imports a new git repository. Any CCF metadata files will then be available to the panhandler
        application

  - name: snippet_types
    class: ListSnippetTypesView
    menu: Panhandler
    menu_option: Template Library

  - name: collections
    class: ListSkilletCollectionsView
    menu: Panhandler
    menu_option: Skillet Collections


  - name: snippets_by_type
    class: ListSnippetsByGroup
    parameter: service_type

  - name: repos
    class: ListReposView
    menu: Panhandler
    menu_option: Repositories

  - name: repo_detail
    class: RepoDetailsView
    parameter: repo_name

  - name: update_repo
    class: UpdateRepoView
    parameter: repo_name

  - name: remove_repo
    class: RemoveRepoView
    parameter: repo_name

  - name: collection
    class: ListSkilletsInCollectionView
    parameter: collection

  - name: skillet
    class: ViewSkilletView
    parameter: skillet

  - name: provision
    class: ProvisionSnippetView


